plugins:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

FactoryBot/SyntaxMethods:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/librum/core/rspec/contracts/**/*.rb
    - lib/librum/core/rspec/examples/**/*.rb
    - spec/**/*_contract*.rb
    - spec/**/*_factories.rb
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Metrics/ModuleLength:
  Exclude:
    - lib/librum/core/rspec/contracts/**/*.rb
    - lib/librum/core/rspec/examples/**/*.rb
    - spec/**/*_contract*.rb

RSpec/BeNil:
  Enabled: false

RSpec/Eq:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: example

RSpec/IncludeExamples:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Exclude:
    - spec/**/*_contract*.rb

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/integration/**/*

RSpec/SpecFilePathSuffix:
  Exclude:
    - '**/*spec.fixture.rb'

RSpecRails/InferredSpecType:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*

Style/NestedParenthesizedCalls:
  Exclude:
    - spec/**/*

Style/RedundantLineContinuation:
  Enabled: false
